info/modules/news/__init__.py
from flask import Blueprint

news_blue = Blueprint('news', __name__, url_prefix='/news')

from . import views

info/modules/news/views.py
from . import news_blue
from flask import current_app, render_template, session, jsonify, request, abort, g

# 请求路径: /news/<int:news_id>
# 请求方式 GET
# 请求参数 news_id
# 返回值: detail.html data字典数据
from ...utils.commons import user_login_data
from ...utils.response_code import RET


# 关注
@news_blue.route('/followed_user', methods=['POST'])
@user_login_data
def followed_user():
    from info.models import User
    if not g.user:
        return jsonify(errno=RET.NODATA, errmsg='用户未登录')

    author_id = request.json.get('user_id')
    action = request.json.get('action')

    if not all([author_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')
    try:
        author = User.query.get(author_id)
    except Exception as e:
        current_app.ogger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='获取作者失败')

    if not author:
        return jsonify(errno=RET.NODATA, errmsg='该作者不存在')
    if g.user.id == author.id:
        return jsonify(errno=RET.NODATA, errmsg='自己不能关注自己')
    if action == 'follow':
        # 判断当前用户是否关注了该作者
        if g.user not in author.followers:
            author.followers.append(g.user)
    else:
        if g.user in author.followers:
            author.followers.remove(g.user)
    return jsonify(errno=RET.OK, errmsg='关注成功')


# 评论点赞
# 请求参数 comment_id, action, g.user
@news_blue.route('/comment_like', methods=['POST'])
@user_login_data
def comment_like():
    from info.models import Comment, CommentLike
    from info import db
    if not g.user:
        return jsonify(errno=RET.NODATA, errmsg='用户未登录')
    comment_id = request.json.get('comment_id')
    action = request.json.get('action')
    if not all([comment_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')
    if action not in ['add', 'remove']:
        return jsonify(errno=RET.DATAERR, errmsg='操作类型有误')
    try:
        comment = Comment.query.get(comment_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='获取评论失败')
    if not comment:
        return jsonify(errno=RET.NODATA, errmsg='评论不存在')
    try:
        if action == 'add':
            # 判断用户是否对当前评论点过赞
            comment_like = CommentLike.query.filter(CommentLike.user_id == g.user.id, CommentLike.comment_id == comment_id).first()
            print(comment_like)
            if not comment_like:
                comment_likes = CommentLike(user_id=g.user.id, comment_id=comment_id)

                db.session.add(comment_likes)

                # 该评论的点赞数量 +1
                comment.like_count += 1
                db.session.commit()
        else:
            # 判断用户是否对当前评论点过赞
            comment_like = CommentLike.query.filter(CommentLike.user_id == g.user.id, CommentLike.comment_id == comment_id).first()
            print(comment_like)
            if comment_like:
                from info import db
                db.session.delete(comment_like)

                # 该评论的点赞数量 +1
                if comment.like_count > 0:
                    comment.like_count -= 1
                db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='操作失败')
    return jsonify(errno=RET.OK, errmsg='操作成功')


# 新闻评论 请求方式 POST， 参数
@news_blue.route('/news_comment', methods=['POST'])
@user_login_data
def news_comment():
    from info.models import News, Comment
    from info import db
    if not g.user:
        return jsonify(errno=RET.NODATA, errmsg='请先登录')
    news_id = request.json.get('news_id')
    content = request.json.get('comment')
    parent_id = request.json.get('parent_id')
    if not all([news_id, content]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='获取新闻失败')
    comment_dic = {
        'user_id': g.user.id,
        'news_id': news_id,
        'content': content,
        'parent_id': parent_id
    }
    comment = Comment(**comment_dic)
    try:
        db.session.add(comment)
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='评论失败')
    return jsonify(errno=RET.OK, errmsg='评论成功', data=comment.to_dict())


# 收藏与取消收藏 参数 新闻id action(是收藏还是取消收藏)
@news_blue.route('/news_collect', methods=['POST'])
@user_login_data
def news_collect():
    # 判断用户是否登录
    if not g.user:
        return jsonify(errno=RET.NODATA, errmsg='请先登录')
    # 获取参数 ajax提交的
    news_id = request.json.get('news_id')
    action = request.json.get('action')

    if not all([news_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')

    # 操作类型校验
    if action not in ['collect', "cancel_collect"]:
        return jsonify(errno=RET.DATAERR, errmsg='操作类型有误')

    # 根据新闻的编号取出新闻来
    try:
        from info.models import News
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='获取新闻失败')
    # 判断新闻对象是否存在
    if not news:
        return jsonify(errno=RET.NODATA, errmsg='新闻不存在')

    # 根据操作类型，进行收藏&取消收藏
    if action == 'collect':
        # 判断用户是否对该新闻做过收藏
        if news not in g.user.collection_news:
            g.user.collection_news.append(news)
    else:
        if news in g.user.collection_news:
            g.user.collection_news.remove(news)
    return jsonify(errno=RET.OK, errmsg='收藏成功')


@news_blue.route('/<int:news_id>')
@user_login_data
def news_detail(news_id):
    from info.models import User, News, Category, Comment, CommentLike
    from ...utils.response_code import RET
    # 从session中取出用户数据
    # user_id = session.get('user_id')
    # user = None
    # if user_id:
    #     try:
    #         user = User.query.get(user_id)
    #     except Exception as e:
    #         current_app.logger.error(e)
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='获取新闻失败')
    if not news:
        abort(404)
    # 获取前6条热门新闻
    try:
        click_news = News.query.order_by(News.clicks.desc()).limit(6).all()
    except Exception as e:
        current_app.logger.error(e)
    # 将热门新闻对象列表转成字典列表
    click_news_list = [news.to_dict() for news in click_news]

    # 判断用户是否收藏过改文章
    is_collected = False
    # 用户需要登录并且该新闻在用户收藏过的新闻列表中
    if g.user:
        if news in g.user.collection_news:
            is_collected = True

    # 查询数据库中，该新闻的所有评论内容
    try:
        comments = Comment.query.filter(Comment.news_id == news_id).order_by(Comment.create_time.desc()).all()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='获取评论失败')
    try:
        commentslikes = []
        if g.user:
            # 用户点赞过的所有评论
            commentslikes = CommentLike.query.filter(CommentLike.user_id == g.user.id).all()
        # 用户点赞过的所有评论id
        mylike_comment_ids = [commentLike.comment_id for commentLike in commentslikes]
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='获取点赞失败')
    comment_list = []
    for comment in comments:
        comm_dict = comment.to_dict()
        # 判断用户是否对评论点过赞  该评论是否在用户点赞列表里
        # if comment.id in mylike_comment_ids:
        comm_dict['is_like'] = comment.id in mylike_comment_ids
        print(comm_dict)
        comment_list.append(comm_dict)

    # 判断登录用户是否关注了新闻的作者
    is_followed = False
    if g.user and news.user:
        if g.user in news.user.followers:
            is_followed = True

    data = {
        'news_info': news.to_dict(),
        'user_info': g.user.to_dict() if g.user else "",
        'news_list': click_news_list,
        'is_collected': is_collected,
        'comments': comment_list,
        'is_followed': is_followed
    }
    return render_template('news/detail.html', data=data)

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titleBlock %}

    {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    {% block scriptBlock %}

    {% endblock %}
    <style>
    </style>
</head>
<body>
<div class="header_con">
    <div class="header">
        <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
        {% block headerBlock %}

        {% endblock %}
        {#判断用户是否登陆#}
        {% if data.user_info %}
            <div class="user_login fr">
                {% if data.user_info.avatar_url %}
                    <img src="{{ data.user_info.avatar_url }}" class="lgin_pic">
                    {% else %}
                    <img src="../../static/news/images/person01.png" class="lgin_pic">
                {% endif %}

                <a href="{{ url_for('profile.user_index') }}">{{ data.user_info.nick_name }}</a>
                <a href="javascript:;" onclick="logout()">退出</a>
                <a href="../../static/news/html/dianmingqi.html">点名器</a>
            </div>
        {% else %}
            <!-- 用户登录后显示下面，隐藏上面 -->
            <div class="user_btns fr">
                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
            </div>
        {% endif %}


    </div>
</div>

<div class="conter_con">
    {% block contentBlock %}

    {% endblock %}
    {# 右边 热门新闻 + 作者部分 #}
    {% block rankBlock %}
        <div class="rank_con fr">
                {% block authorBlock %}

                {% endblock %}
            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
                <ul class="rank_list">
                    {% for item in data.news_list %}
                        {# 根据遍历索引设置标签的样式 #}
                        {# 第一种方式 #}
        {#                {% if loop.index==1 %}#}
        {#                    <li><span class="first">{{ loop.index }}</span><a href="#">{{ item.title }}</a></li>#}
        {#                {% elif loop.index==2 %}#}
        {#                    <li><span class="second">{{ loop.index }}</span><a href="#">{{ item.title }}</a></li>#}
        {#                {% elif loop.index==3 %}#}
        {#                    <li><span class="third">{{ loop.index }}</span><a href="#">{{ item.title }}</a></li>#}
        {#                {% else %}#}
        {#                    <li><span class="">{{ loop.index }}</span><a href="#">{{ item.title }}</a></li>#}
        {#                {% endif %}#}
                        {#第二种方式过滤器#}
                        <li><span class="{{ loop.index | my_filter }}">{{ loop.index }}</span><a href="{{ url_for('news.news_detail', news_id=item.id) }}">{{ item.title }}</a></li>
                    {% endfor %}


                    {#
                        <li><span class="first">1</span><a href="#">势如破竹！人民币再度连闯四道关口 在岸、离岸双双升破6.42</a></li>
                        <li><span class="second">2</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>
                        <li><span class="third">3</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>
                        <li><span>4</span><a href="#">势如破竹！人民币再度连闯四道关口 在岸、离岸双双升破6.42</a></li>
                        <li><span>5</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>
                        <li><span>6</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>#}
                </ul>
            </div>
    {% endblock %}

</div>
<div class="footer">
    <div class="footer_links">
        <a href="">关于我们</a>
        <span>|</span>
        <a href="">联系我们</a>
        <span>|</span>
        <a href="">招聘人才</a>
        <span>|</span>
        <a href="">友情链接</a>
    </div>
    <p class="copyright">
        CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br/>
        电话：010-****888 京ICP备*******8号
    </p>
</div>

<!-- 登录表单 -->
<form class="login_form_con">
    <div class="login_form">
        <div class="login_title">
            <h3>登 录</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input id="mobile" type="text" name="mobile" autocomplete="off">
            <div class="input_tip">手机号</div>
            <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input id="password" type="password" name="password">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="login-password-err" class="error_tip">密码不能为空</div>
        </div>
        <input type="submit" name="" value="登 录" class="input_sub">
        <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
    </div>
    <div class="mask"></div>
</form>

<!-- 注册表单 -->
<form class="register_form_con">
    <div class="register_form">
        <div class="register_title">
            <h3>注 册</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
            <div class="input_tip">手机号</div>
            <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
            <div class="input_tip">图形验证码</div>
            <img src="/passport/image_code" class="get_pic_code" onclick="generateImageCode()">
            <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="smscode" id="smscode" class="code_pwd">
            <div class="input_tip">手机验证码</div>
            <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
            <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
        </div>
        <div class="form_group">
            <input type="password" name="password" id="register_password" class="pass_input">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="register-password-err" class="error_tip">密码不能为空</div>
        </div>
        <div class="form_group2 clearfix">
            <input type="checkbox" class="agree_input" checked>
            <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
            <div class="error_tip">请勾选</div>
        </div>
        <input type="submit" name="" value="注 册" class="input_sub">
        <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
    </div>
    <div class="mask"></div>
</form>

</body>
</html>

info/templates/news/index.html
{% extends 'news/base.html' %}
{% block titleBlock %}
    文章详情页
{% endblock %}
{% block scriptBlock %}
    <script src="../../static/news/js/index.js"></script>
{% endblock %}
{% block headerBlock %}
    <ul class="menu fl">
    {% for category in data.category_list %}
        <li class="{% if loop.index0 == 0 %}active{% endif %}" data-cid="{{ category.id }}"><a
                href="javascript:;">{{ category.name }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}
{% block contentBlock %}
    <ul class="list_con fl">
        <span style="color: red;">正在拼命加载数据....</span>
    </ul>
{% endblock %}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>首页-新经资讯</title>#}
{#    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">#}
{#    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">#}
{#    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>#}
{#    <script type="text/javascript" src="../../static/news/js/main.js"></script>#}
{#    <script type="text/javascript" src="../../static/news/js/index.js"></script>#}
{#    <style>#}
{#    </style>#}
{#</head>#}
{#<body>#}
{#<div class="header_con">#}
{#    <div class="header">#}
{#        <a href="#" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>#}
{#        <ul class="menu fl">#}
{#            {% for category in data.category_list %}#}
{#            <li class="{% if loop.index0 == 0 %}active{% endif %}" data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>#}
{#            {% endfor %}#}
{#            #}
{#            <li class="active" data-cid="1"><a href="javascript:;">最新</a></li>#}
{#            <li data-cid="2"><a href="javascript:;">股市</a></li>#}
{#            <li data-cid="3"><a href="javascript:;">债市</a></li>#}
{#            <li data-cid="4"><a href="javascript:;">商品</a></li>#}
{#            <li data-cid="5"><a href="javascript:;">外汇</a></li>#}
{#            <li data-cid="6"><a href="javascript:;">公司</a></li>#}
{#        </ul>#}
{#判断用户是否登陆#}
{#        {% if data.user_info %}#}
{#            <div class="user_login fr">#}
{#                <img src="../../static/news/images/person01.png" class="lgin_pic">#}
{#                <a href="#">{{ data.user_info.nick_name }}</a>#}
{#                <a href="#" onclick="logout()">退出</a>#}
{#            </div>#}
{#        {% else %}#}
{#            <!-- 用户登录后显示下面，隐藏上面 -->#}
{#            <div class="user_btns fr">#}
{#                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>#}
{#            </div>#}
{#        {% endif %}#}
{##}
{##}
{#    </div>#}
{#</div>#}
{##}
{#<div class="conter_con">#}
{#    <ul class="list_con fl">#}
{#        <li>#}
{#            <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>#}
{#            <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市软银计划将手机业务分拆上市</a>#}
{#            <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank#}
{#                Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>#}
{#            <div class="author_info fl">#}
{#                <div class="author fl">#}
{#                    <img src="../../static/news/images/person.png" alt="author">#}
{#                    <a href="#">乐鸣</a>#}
{#                </div>#}
{#                <div class="time fl">2017-01-01 00:00:00</div>#}
{#            </div>#}
{#        </li>#}
{#        <li>#}
{#            <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>#}
{#            <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>#}
{#            <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank#}
{#                Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>#}
{#            <div class="author_info fl">#}
{#                <div class="source fl">#}
{#                    来源：广州日报#}
{#                </div>#}
{#                <div class="time fl">2017-01-01 00:00:00</div>#}
{#            </div>#}
{#        </li>#}
{#        <li>#}
{#            <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>#}
{#            <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>#}
{#            <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank#}
{#                Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>#}
{#            <div class="author_info fl">#}
{#                <div class="author fl">#}
{#                    <img src="../../static/news/images/person.png" alt="author">#}
{#                    <a href="#">乐鸣</a>#}
{#                </div>#}
{#                <div class="time fl">2017-01-01 00:00:00</div>#}
{#            </div>#}
{#        </li>#}
{#        <li>#}
{#            <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>#}
{#            <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>#}
{#            <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank#}
{#                Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>#}
{#            <div class="author_info fl">#}
{#                <div class="source fl">#}
{#                    来源：广州日报#}
{#                </div>#}
{#                <div class="time fl">2017-01-01 00:00:00</div>#}
{#            </div>#}
{#        </li>#}
{#    </ul>#}
{#    <div class="rank_con fr">#}
{#        <div class="rank_title">#}
{#            <h3>点击排行</h3>#}
{#        </div>#}
{#        <ul class="rank_list">#}
{#            {% for item in data.news %}#}
{# 根据遍历索引设置标签的样式 #}
{# 第一种方式 #}
{#                {% if loop.index==1 %}#}
{#                    <li><span class="first">{{ loop.index }}</span><a href="#">{{ item.title }}</a></li>#}
{#                {% elif loop.index==2 %}#}
{#                    <li><span class="second">{{ loop.index }}</span><a href="#">{{ item.title }}</a></li>#}
{#                {% elif loop.index==3 %}#}
{#                    <li><span class="third">{{ loop.index }}</span><a href="#">{{ item.title }}</a></li>#}
{#                {% else %}#}
{#                    <li><span class="">{{ loop.index }}</span><a href="#">{{ item.title }}</a></li>#}
{#                {% endif %}#}
{#第二种方式过滤器#}
{#                <li><span class="{{ loop.index | my_filter }}">{{ loop.index }}</span><a href="#">{{ item.title }}</a></li>#}
{#            {% endfor %}#}
{##}
{#
{#                <li><span class="first">1</span><a href="#">势如破竹！人民币再度连闯四道关口 在岸、离岸双双升破6.42</a></li>#}
{#                <li><span class="second">2</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>#}
{#                <li><span class="third">3</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>#}
{#                <li><span>4</span><a href="#">势如破竹！人民币再度连闯四道关口 在岸、离岸双双升破6.42</a></li>#}
{#                <li><span>5</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>#}
{#                <li><span>6</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>#}
{#        </ul>#}
{#    </div>#}
{#</div>#}
{#<div class="footer">#}
{#    <div class="footer_links">#}
{#        <a href="">关于我们</a>#}
{#        <span>|</span>#}
{#        <a href="">联系我们</a>#}
{#        <span>|</span>#}
{#        <a href="">招聘人才</a>#}
{#        <span>|</span>#}
{#        <a href="">友情链接</a>#}
{#    </div>#}
{#    <p class="copyright">#}
{#        CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br/>#}
{#        电话：010-****888 京ICP备*******8号#}
{#    </p>#}
{#</div>#}
{##}
{#<!-- 登录表单 -->#}
{#<form class="login_form_con">#}
{#    <div class="login_form">#}
{#        <div class="login_title">#}
{#            <h3>登 录</h3>#}
{#            <a href="javascript:;" class="shutoff"></a>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input id="mobile" type="text" name="mobile" autocomplete="off">#}
{#            <div class="input_tip">手机号</div>#}
{#            <div id="login-mobile-err" class="error_tip">手机号不能为空</div>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input id="password" type="password" name="password">#}
{#            <div class="input_tip">密码(不少于6位)</div>#}
{#            <div id="login-password-err" class="error_tip">密码不能为空</div>#}
{#        </div>#}
{#        <input type="submit" name="" value="登 录" class="input_sub">#}
{#        <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>#}
{#    </div>#}
{#    <div class="mask"></div>#}
{#</form>#}
{##}
{#<!-- 注册表单 -->#}
{#<form class="register_form_con">#}
{#    <div class="register_form">#}
{#        <div class="register_title">#}
{#            <h3>注 册</h3>#}
{#            <a href="javascript:;" class="shutoff"></a>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">#}
{#            <div class="input_tip">手机号</div>#}
{#            <div id="register-mobile-err" class="error_tip">手机号不能为空</div>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="text" name="code_pwd" id="imagecode" class="code_pwd">#}
{#            <div class="input_tip">图形验证码</div>#}
{#            <img src="/passport/image_code" class="get_pic_code" onclick="generateImageCode()">#}
{#            <div id="register-image-code-err" class="error_tip">图形码不能为空</div>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="text" name="smscode" id="smscode" class="code_pwd">#}
{#            <div class="input_tip">手机验证码</div>#}
{#            <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>#}
{#            <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="password" name="password" id="register_password" class="pass_input">#}
{#            <div class="input_tip">密码(不少于6位)</div>#}
{#            <div id="register-password-err" class="error_tip">密码不能为空</div>#}
{#        </div>#}
{#        <div class="form_group2 clearfix">#}
{#            <input type="checkbox" class="agree_input" checked>#}
{#            <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>#}
{#            <div class="error_tip">请勾选</div>#}
{#        </div>#}
{#        <input type="submit" name="" value="注 册" class="input_sub">#}
{#        <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>#}
{#    </div>#}
{#    <div class="mask"></div>#}
{#</form>#}
{#</body>#}
{#</html>#}